### ISSUE TITLE
back up module for all meta data

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#5207]
Take existing contacts backup module and extend it to all app metadata. There should be a single module (accessible from app settings) to backup app all app metadata:

- [x] payment contacts
- [x] coins in the watchlist
- [x] watched wallets
- [x] app appearance settings
- [ ] app security settings

## 1) New Manage Wallets Implementation

- [x] **Import Wallet**
- from Recovery Phrase
- from iCloud
- from Files
- from Exchange
<img width="226" alt="Screenshot 2023-09-28 at 15 27 17" src="https://github.com/horizontalsystems/unstoppable-wallet-ios/assets/22589457/58cc009a-14be-468c-862b-6613a0260b15">

- [x] Add the "Backup Manager" section to the Settings

## 2) Backup Manager -- Create

- [x] **Creating a new settings backup:** Users can create backups of their wallets, contacts, and application settings. Two storage options will be available for backups:

- Saving to iCloud.
- Saving to Files (system file manager).

- [x] **Selective Backup:** Users have the option to choose which wallets they want to include in the backup. By default, other settings such as watch wallets, contacts, and blockchain settings will also be backed up.

- [ ] Text Backup to iCloud
> iCloud is a cloud storage service provided by Apple. It's important to know that your backup data will be stored on Apple's servers.
>> I understand that losing access to my iCloud will result in losing access to the backup of a respective wallet.

- [ ]  Text Backup to Files
> Storage devices i.e. hard drives, USB drives, storage on smartphones, etc. are all vulnerable to loss due to physical damage, theft, or other unforeseen circumstances.
>> I understand that theft or damage of a backup device will result in the loss of a backup to a respective wallet.

- [ ] **Setting a Password:** When creating a backup, users will be required to set a password, which must consist of at least 8 characters.

- [ ] **Notification and Redirection:** After successfully creating a backup, users will receive a notification and will be redirected to the "Backup Manager" page to manage their backups.

## 3) **Backup Manager -- Restore** 

Currently, our application has two locations where users can restore the backup app. 

- Manage Wallet -> Import Wallet
This location will primarily focus on wallet restoration but will also include the option to restore other settings.

- "Settings -- Backup Manager
This location will be dedicated to creating and restoring backups, including wallets, contacts, and other application settings.

 ### **From iCloud**

- [ ] When selecting this option, the user will be directed to a page that shows all the backups stored in iCloud. These backups are categorized under the headers "Wallets Backup" and "App Backups".

- [ ] To restore a file, the user needs to enter the password associated with the corresponding backup.

- [ ] After successfully entering the password, the contents of the backup file will be revealed.

- [ ] If the user already has restored wallets and contacts and wishes to restore another backup file, a notification with a bottom shield will appear, prompting the user to merge the data.

### **From Files**

- [ ] When selecting this option, the user will be directed to the system file manager page.

- [ ] To restore a file, the user needs to enter the password associated with the corresponding backup.

- [ ] After successfully entering the password, the contents of the backup file will be revealed.

- [ ] If the user already has restored wallets and contacts and wishes to restore another backup file, a notification with a bottom shield will appear, prompting the user to merge the data.

**Comment by Dianaaiym** [comment]
Need to fix:

- [ ] Create New Backup: If there are no wallets in the app, the wallet title does not need to be displayed.
![2023-10-13 12 27 47](https://github.com/horizontalsystems/unstoppable-wallet-ios/assets/22589457/e441b664-2a78-426e-9410-375a47ce883a)

- [ ] Create New Backup: The checkbox should be empty initially (Uncheck)

![2023-10-13 12 29 49](https://github.com/horizontalsystems/unstoppable-wallet-ios/assets/22589457/b7e641bf-42cc-498d-9208-9b91783878c7)

- [ ] Create New Backup:  Set up password -  change text to "Password cannot be empty"
![2023-10-13 12 30 42](https://github.com/horizontalsystems/unstoppable-wallet-ios/assets/22589457/c9d785ac-6917-42d8-bab1-7225944f4060)

- [ ] Restore Backup: If there are no contacts in the wallet, the bottom sheet should not appear when importing the backup of the app.
![2023-10-13 12 32 04](https://github.com/horizontalsystems/unstoppable-wallet-ios/assets/22589457/fa817720-c4e1-4014-af8b-1a6c0e98a8fa)

- [ ]  Create New Backup: Change hud text (Saved in Files) for successful backup app creation
![2023-10-13 12 35 25](https://github.com/horizontalsystems/unstoppable-wallet-ios/assets/22589457/e5567d73-9648-4d88-a2da-107cf380c514)
